### PR TITLE
@ashfurrow => Update to modern tech

### PR DESCRIPTION
**Pull request by orta**
Got this up and running on Xcode 6.3.2, Quick being swift means that it's Xcode specific :-/

### CODE REVIEW

**Comment by ashfurrow** [comment]
Makes sense. Everything looks good but th reds.

**Comment by ashfurrow** [comment]
Linker error on Travis:

```
ld: warning: directory not found for option '-F/Users/travis/build/artsy/Artsy_Authentication/Example/Pods/build/Debug-iphoneos/Pods-Tests'
ld: framework not found Pods
```

**Comment by orta** [comment]
I'll have some time for this today :+1:

**Comment by orta** [comment]
Green

**Pull request merged**
